---
- name: GET request to an API
  hosts: localhost
  connection: local
  tasks:
    - name: Send GET request to SWAPI
      uri:
        url: https://swapi.dev/api/people/69/`
        method: GET
        return_content: yes
      register: api_response

    - name: Display the API response
       debug:
        var: api_response.content
          


